# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alex/GitHub/zynq-ip-cores/crypto_wrapper/crypto_wrapper.srcs/sources_1/ip/present_0/present_0.xci
# IP: The module: 'present_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/alex/GitHub/zynq-ip-cores/crypto_wrapper/crypto_wrapper.srcs/sources_1/ip/present_0/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dwidth_converter_0 || ORIG_REF_NAME==axis_dwidth_converter_0} -quiet] -quiet

# IP: /home/alex/GitHub/zynq-ip-cores/crypto_wrapper/crypto_wrapper.srcs/sources_1/ip/present_0/sources_1/ip/axis_dwidth_converter_1/axis_dwidth_converter_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dwidth_converter_1 || ORIG_REF_NAME==axis_dwidth_converter_1} -quiet] -quiet

# IP: /home/alex/GitHub/zynq-ip-cores/crypto_wrapper/crypto_wrapper.srcs/sources_1/ip/present_0/present_0.xci
# IP: The module: 'present_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/alex/GitHub/zynq-ip-cores/crypto_wrapper/crypto_wrapper.srcs/sources_1/ip/present_0/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dwidth_converter_0 || ORIG_REF_NAME==axis_dwidth_converter_0} -quiet] -quiet

# IP: /home/alex/GitHub/zynq-ip-cores/crypto_wrapper/crypto_wrapper.srcs/sources_1/ip/present_0/sources_1/ip/axis_dwidth_converter_1/axis_dwidth_converter_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dwidth_converter_1 || ORIG_REF_NAME==axis_dwidth_converter_1} -quiet] -quiet
